### ISSUE TITLE
l10n: Strings from "src" directory

### ISSUE THREAD

**Issue by Valdnet** [Raudius/files_scripts#1]
In Transifex, text strings are incomplete. Strings are missing which are found in files in the "src" directory.

**Comment by Raudius** [comment]
Hi,
Thanks a lot for this report, I thought was being a bit "clever" in the front-end code in the way I did translations. This approach has backfired a bit 

I just pushed a fix so hopefully they should appear on the next sync.

Also, I find it amazing that the app is already being translated, I haven't even had time to put it on the app store!
Great community :blue_heart:

**Comment by Valdnet** [comment]
New text strings have now appeared in Transifex 👍. Thanks.

> Also, I find it amazing that the app is already being translated, I haven't even had time to put it on the app store!

There is a plus of that. The app may come out already partially translated, only a new version needs to be released 😉.
