### ISSUE TITLE
Actions in context menu

### ISSUE THREAD

**Issue by Io-Qo** [Raudius/files_scripts#102]
I find the possiblity to link file actions in the file menu extremely useful and it's greatly appreciated. However, I would prefer to be able to define it for every file action separately, otherwise the menu gets cluttered. So the "More actions" should always be there but you can also link/highlight individual actions in the menu which would make it more tidy imo.

**Comment by ostasevych** [comment]
I found that the actions in context menu doesn't work, if needed to select several documents for parsing, eg, merge pdf files. In this case, the context menu action leads to adding only one specifically selected document for further processing. So, this should be rethought somehow.

**Comment by Raudius** [comment]
This was implemented with #141 and will be part of the `4.0.0` release.

Due to changes with the Files app, this release will only be for NC28+, this saves me having to maintain two integrations with the old and new files app versions.
