### ISSUE TITLE
Executing Merge PDFs example script leads to errors

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#106]
Hi! I have set up file actions app, install lua according to the updated readme as of today,
I have added row `extension=lua.so` both to `/etc/php/8.1/apache2/conf.d/@20-lua.ini` and `/etc/php/8.1/cli/conf.d/@20-lua.ini`

![image](https://github.com/Raudius/files_scripts/assets/5199030/af6e0f24-608a-43f6-8a25-11e966cb83ff)

I do not see either the folder or the resulting file prompt at all if to compare with the screenshot from the app description:
![image](https://github.com/Raudius/files_scripts/assets/5199030/9ebfc5a7-83b7-48e4-ad4a-a11c24150337)

Trying to test it with the [Merge PDFs](https://github.com/Raudius/files_scripts/blob/master/examples/merge_pdfs.lua) example script, which is provided with the app, I am constantly getting error 
`[string "line"]:8: attempt to call a nil value (global 'get_target_folder')`

Ubuntu 22.04
Apache2.4.52
PHP 8.1.2
Nextcloud 26.0.5
qpdf 10.6.3

What may be wrong?

**Comment by ostasevych** [comment]
UPD After updating the script as per https://github.com/Raudius/files_scripts/blob/master/examples/merge_pdfs.lua
I am getting a new error: `No filename is provided`.

**Comment by Raudius** [comment]
For some reason the inputs didnt get added with the sample script.

You should add these:

![image](https://github.com/Raudius/files_scripts/assets/3178979/e89b6037-476b-48bd-a0af-be4c56201e23)

![image](https://github.com/Raudius/files_scripts/assets/3178979/692fde7b-069f-4f84-8d05-fdf43ffd0d43)

![image](https://github.com/Raudius/files_scripts/assets/3178979/f84d8104-1aba-4d87-9431-8dd693ca8f3c)

**Comment by Raudius** [comment]
Trying to think what might have gone wrong?

There was a bug in a previous version which didnt properly include the variables. Is it possible you installed the app a while back?

This would also explain that the sample script still had the deprecated function `get_target_folder`

**Comment by ostasevych** [comment]
Hi! I have added these variables, exactly the same, as you have mentioned. However, the script doesn't merge pdf files, but outputs the first one in the list...

**Comment by Raudius** [comment]
> 2. Call script from the files menu close to one of these 3 files.

If you mean the `...` menu, near a file. It will only show the actions for that file. This is how the Nextcloud files app works in general, you can test also selecting multiple files and trying the delete option (it will only delete the selected file)

![image](https://github.com/Raudius/files_scripts/assets/3178979/55543cdd-6a0e-4b5f-95a9-71d4318356ab)

**Comment by ostasevych** [comment]
> > 2. Call script from the files menu close to one of these 3 files.
> 
> If you mean the `...` menu, near a file. It will only show the actions for that file. This is how the Nextcloud files app works in general, you can test also selecting multiple files and trying the delete option (it will only delete the selected file)
> 
> ![image](https://user-images.githubusercontent.com/3178979/263553779-55543cdd-6a0e-4b5f-95a9-71d4318356ab.png)

Yes, exactly! Actually, I thought it will apply the action to all selected files, though thanks for the explanations. Perhaps it might be a good idea to add some switcher: to show the script in direct menu or not to show?
