### ISSUE TITLE
Add a new example script: OCR document

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#107]
Hi! Let me suggest to add a new example to the list of scripts: OCR document.
With it a user may select some PDF document, select languages, and select output file (either to use the same or create a new file (optionally)). The tesseract and installed languages are required.

Will it be possible to do it?

**Comment by ostasevych** [comment]
So, what I have investigated on how to OCR PDF files:
1. https://unix.stackexchange.com/questions/301318/how-to-ocr-a-pdf-file-and-get-the-text-stored-within-the-pdf
2. pdf2searchablepdf mypdf.pdf will do the job, see https://github.com/ElectricRCAircraftGuy/PDF2SearchablePDF
3. ocrmypdf 1.pdf res.pdf --skip-text --output-type pdf, will do the job as well

**Comment by Raudius** [comment]
Hey!

Its possible to manage input and output to scripts using the `meta_data(file).local_path` property. Which gives the full local path of the file on the server.

Here is roughly what you would need to do (note that the code is unpolished and untested)

```lua
-- TODO: add more checks to this, like how to handle if multiple files are selected
input_file = get_input_files()[1] 

-- Create a file called "OCR_[input file name]"
dir = get_parent(input_file)
output_name = "OCR_" .. input_file.name
output_file = new_file(dir, output_name) 
-- TODO: check the file creation failed (output_file == nil) and abort if necessary 

input_path = meta_data(input_file).local_path
output_path = meta_data(output_file).local_path

command_tpl = "ocrmypdf %s %s --skip-text --output-type pdf"
command = command_tpl:format(input_path, output_path)

result = shell_command(command)
-- TODO: handle result
```

**Comment by ostasevych** [comment]
> Hey!
> 
> Its possible to manage input and output to scripts using the `meta_data(file).local_path` property. Which gives the full local path of the file on the server.
> 
> Here is roughly what you would need to do (note that the code is unpolished and untested)
> 

Hi! Many-many thanks! I would like to adapt the script by adding language attribute, however, it is a bit more complicated, as languages are provided in the following way:

`ocrmypdf --language ukr+eng input.pdf output.pdf`

So, if I need to select 2 or more languages, I have to add "+" sign between them. Would you be so kind to help to understand, how to handle it?

My updated script with your improvements:

```
-- TODO: add more checks to this, like how to handle if multiple files are selected
local input_file = get_input_files()[1] 

-- Create a file called "OCR_[input file name]"
-- local dir = get_parent(input_file)
local dir = get_input("output_location")
local output_name = get_input("file_name")
local select_languages = get_input("ocr_languages")

if (select_languages == nil or select_languages == "") then
  	select_languages = "ukr+eng"
end

if (output_name == nil or output_name == "") then
  	output_name = "OCR_" .. input_file.name
end

if (string.find(output_name, ".pdf") == nil) then
	output_name = output_name .. ".pdf"
end

output_file = new_file(dir, output_name)

 -- TODO: check the file creation failed (output_file == nil) and abort if necessary 

input_path = meta_data(input_file).local_path
output_path = meta_data(output_file).local_path
ocr_lang = meta_data(select_languages).local_path

-- input_path = meta_data(input_file)
-- output_path = meta_data(output_file)


command_tpl = "ocrmypdf %s %s --language %s --skip-text --output-type pdf"
command = command_tpl:format(input_path, output_path, ocr_lang)

result = shell_command(command)
-- TODO: handle result
```

**Comment by Raudius** [comment]
Hi

`meta_data` should only be used for files, which gives you a file object with extra information (like `local_path`). 

In this case I assume the `select_languages` is a multi-select input that allows for selection of multiple options. Something like this
![image](https://github.com/Raudius/files_scripts/assets/3178979/bec33edb-ed7f-4768-860c-43f0c673c6be)


In the case of a multi-select input, the returned value of `get_input` will be a Lua table (array). You can then use `table.concat` to join the values with the chosen string. In your case `"+"`.

```lua
select_languages = get_input("ocr_languages")   -- e.g. {"en", "fr", "de"}
ocr_lang = table.concat(select_languages, "+")  -- e.g. "en+fr+de"
```

**Comment by ostasevych** [comment]
> Hi
> 
> `meta_data` should only be used for files, which gives you a file object with extra information (like `local_path`).
> 
> In this case I assume the `select_languages` is a multi-select input that allows for selection of multiple options. Something like this ![image](https://user-images.githubusercontent.com/3178979/263757744-bec33edb-ed7f-4768-860c-43f0c673c6be.png)
> 
> In the case of a multi-select input, the returned value of `get_input` will be a Lua table (array). You can then use `table.concat` to join the values with the chosen string. In your case `"+"`.
> 
> ```lua
> select_languages = get_input("ocr_languages")   -- e.g. {"en", "fr", "de"}
> ocr_lang = table.concat(select_languages, "+")  -- e.g. "en+fr+de"
> ```

Hi! 

With:
```
local select_languages = get_input("ocr_languages")
ocr_lang = table.concat(select_languages, "+")
command_tpl = "ocrmypdf %s %s -l %s --skip-text --image-dpi 150 --output-type pdf"
command = command_tpl:format(input_path, output_path, ocr_lang)
```

I've got a reply:
[string "line"]:30: bad argument #1 to 'concat' (table expected, got string)****

**Comment by ostasevych** [comment]
Raudius, I've added the command to set the default language equal to English

if (select_languages == nil or select_languages == "") then
  	select_languages = "eng"
end

When I skip adding language, I am getting error `[string "line"]:29: bad argument #1 to 'concat' (table expected, got string)`
Exactly on the line 29 I have the string `ocr_lang = table.concat(select_languages, "+")`
How to use default values in this case, eg: "eng" or "eng+fra"?

**Comment by Raudius** [comment]
You can set the default as a table, I would implement it like this:

```lua
if (type(select_languages) ~= "table" or #select_languages == 0) then
    select_languages = { "eng" }
end

ocr_lang = table.concat(select_languages, "+")  
```

**Comment by ostasevych** [comment]
Great. Quite interesting syntaxis. One more question: I would like to add current time stamps to files, if the name is not provided, eg `result_28082023_1939.pdf`.

I found that there's a function create_date_time(). How to make the correct concatenation of the date stamp to the name?
```
if (name == nil or name == "") then
  		name = "Result_" .. current_date_stamp
end
```

Thanks again?

**Comment by ostasevych** [comment]
> You can use something like this:
> 
> ```lua
> now = create_date_time()
> timezone = "CET"
> format = "ddMMyyyy_HHmm"
> 
> current_date_stamp = format_date_time(now, nil, timezone, format)
> ```

Many thanks! Meanwhile, where to find more to read about the syntaxis? I'd like to have more practice :)

What I found a bit missing, is setting some default values to variables in UI settings. Perhaps, this may be added somehow?
