### ISSUE TITLE
File activities

### ISSUE THREAD

**Issue by ossie** [Raudius/files_scripts#109]
It would be a great enhancement if the API allowed access to file activity as well. 
My aim is to export a file approval protocol based on the approval flow in the file activities.

**Comment by Raudius** [comment]
Hi ossie, thanks for the suggestion.

I dont use the activity app myself, so could you go into a bit more detail on what sort of functions could be added to the API that interface with the activity app?

**Comment by ossie** [comment]
Hi Raudius, 
the important information I would need is: who in the approval flow gave approval at which point in time? 
In the german frontenend it looks like this in the file details: "[user] hat [document name] zugestimmt]"
![image](https://github.com/Raudius/files_scripts/assets/462735/bcd53c50-05bc-440a-90b6-18711e958c22)
I appreciate any function which returns a table containing alle file activities in a readable format including the time stamp.

**Comment by Raudius** [comment]
Sorry it took some time to implement but this feature should be implemented in the next release following #122 

Not sure when this will be released but I aim to publish the release before NC28 comes out.
