### ISSUE TITLE
How to notify user?

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#112]
Hi! Please, help to understand, how to call alert in the script? Eg, to notify with the help of Nextcloud notifications.

Eg, when successful there's this one notification

![image](https://github.com/Raudius/files_scripts/assets/5199030/5232f131-7010-43fd-a488-985aab03f8d9)

Is it possible to place some text here, that an operation was partially or not successful at all.

**Comment by ostasevych** [comment]
And one more question: how to analyse the result? Eg, if the command results some error.

**Comment by ostasevych** [comment]
My case to avoid processing non-convertable pairs and alert about that:
```
...
if 
   (input_file.name:match("[^.]+$") == output_format) then
  	do return "Cannot convert in the same format." end

elseif 
   (input_file.name:match("[^.]+$") == "pdf" or input_file.name:match("[^.]+$") == "jpg" 
    or input_file.name:match("[^.]+$") == "png" or input_file.name:match("[^.]+$") == "svg" 
    or input_file.name:match("[^.]+$") == "svg" or input_file.name:match("[^.]+$") == "pptx"
    or input_file.name:match("[^.]+$") == "xlsx" or input_file.name:match("[^.]+$") == "odp"
    or input_file.name:match("[^.]+$") == "ods" or input_file.name:match("[^.]+$") == "csv"
    and output_format == "txt") or 
    ((input_file.name:match("[^.]+$") == "txt" or input_file.name:match("[^.]+$") == "docx" 
    or input_file.name:match("[^.]+$") == "pptx" or input_file.name:match("[^.]+$") == "odp" 
    or input_file.name:match("[^.]+$") == "pptx" or input_file.name:match("[^.]+$") == "xlsx" 
    or input_file.name:match("[^.]+$") == "odp" or input_file.name:match("[^.]+$") == "ods" 
    or input_file.name:match("[^.]+$") == "csv") and (output_format == "jpg" or output_format == "png")) 
  
  then
  	do return "Cannot convert to the selected format. Choose another format." end

else
	output_name = input_file.name:match("(.+)%..+") .. "." .. output_format
	output_file = new_file(dir, output_name)
...

end
```

**Comment by Raudius** [comment]
> how to call alert in the script

You can create the "alert" by using `add_message()`

See example:
```lua
add_message("Blue")  
add_message("Red", "error")  
add_message("Orange", "warning")  
add_message("Green", "success")  
```


> to notify with the help of Nextcloud notifications

Notifications are different, you can think of them as alerts that get handled by the backend. These get shown to the user on every page load until they dismiss them.

```lua
users_found = users_find() -- try to find current user
-- users_found = users_find("Alice") -- try to find user by their profile name "Alice"
-- users_found = users_find(nil, "admin") -- try to find user by UUID "admin"

if (#users_found > 0) then
  notify(user, "Hello world!")
end
```


> how to analyse the result? 

You can see the result of a shell comand by observing the returned table.  Just as a quick example:

```lua
command = 'echo "hello world"'  
result = shell_command(command)

add_message(json(result))
```

**Comment by ostasevych** [comment]
Hi Rauidius! As usual, it is good to have a look to docs :)) I've found in the documentation for devs the function abort(), which allows to notify users about. So, I've used it.

**Comment by ostasevych** [comment]
One more question: unoconv utility is deprecated, so if I output its result it gives a lot of garbage. Is it possible to handle the status code of some command executing? If it differs from 0 break and provide some output for user?

**Comment by Raudius** [comment]
Yes, the exit code is part of the result payload

```
result.exit_code
```
