### ISSUE TITLE
Add the scripts functionality to the clients

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#116]
Hi! Please, think about adding the scripts functionality at the clients side, so that a user may **use** the scripts both on desktop and mobile clients. This will help to automatise the processes.

**Comment by Raudius** [comment]
The clients (desktop/mobile) are developed by Nextcloud, and there is currently no way to integrate with them in such a way.

**Comment by ostasevych** [comment]
Hi! What are the challenges to adding this functionality to the mobile client? Eg this will simplify working with files, eg, creating PDFs, converting image files, and a lot of other operations, which are not and probably will not covered natively by the client but can be performed using the cloud. So, there is only one need to add the UI to the mobile client. 

In October I created the feature request https://github.com/nextcloud/android/issues/12038. It is still without any comment, sadly...

**Comment by Raudius** [comment]
The ball is on Nextcloud's court to allow third party applications to integrate with their clients. Without that there is nothing I can do to advance this issue.

If and when this is possible I would happily integrate with their API.

**Comment by ostasevych** [comment]
> The ball is on Nextcloud's court to allow third party applications to integrate with their clients. Without that there is nothing I can do to advance this issue.
> 
> If and when this is possible I would happily integrate with their API.

So, what to do? Is that possible to push that somehow, especially taking into account your important app which IMHO extends significantly the functionality of NC itself?
