### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by leguennec-meae** [Raudius/files_scripts#117]
Migration script fails (Version020100Date20221126.php) when some inputs are already stored in database.  
column options of the filescript_inputs table should not be set at notnull => false or true plus a default value.

**Comment by Raudius** [comment]
Hi, thanks for the report. I will fix this in the next release.

Were you able to fix the problem on your server?

**Comment by leguennec-meae** [comment]
Yes, we deleted the existing scripts  and then we had no problem to patch
