### ISSUE TITLE
php-fpm is not supported?

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#120]
Hi! I've tried to switch from generic php8.2 to php8.2-fpm in order to get use of http2. However, your app said that there's no installed lua :( I've checked that the 20-lua.ini PHP module is present, but that didn't help.

May I ask you to check that?

**Comment by Raudius** [comment]
Its always tricky when managing multiple PHP installations. Are you sure that the `lua.so` file you compiled is in the correct extensions directory?

**Comment by ostasevych** [comment]
> Its always tricky when managing multiple PHP installations. Are you sure that the `lua.so` file you compiled is in the correct extensions directory?

Well, I've just copied 20-lua.ini from /etc/php/php8.2/apache2/conf.d to /etc/php/php8.2/fpm/conf.d. And that is symlink. With apache2 it works, but with fpm refuses...

**Comment by Raudius** [comment]
I am not sure what that ini file is. The plugin file should be a `.so`.

Recompilong might not be necessary if it's the same PHP version.
