### ISSUE TITLE
Operations with dates

### ISSUE THREAD

**Issue by alessiodeia** [Raudius/files_scripts#121]
Hi, I can't find a way to add 30 days to current date
I need to create a public link with the expiry date 30 days from the current date, but don't know how to do it.
I'vre tried something like this 
`date_expiry= create_date_time()
date_expiry.month=date_expiry.month+1
date_expiry.day=date_expiry.day+10
log("Day= " .. date_expiry.day, 1)
log("Month= " .. date_expiry.month, 1)`

but i get something like Day = 41 or Month= 13

**Comment by Raudius** [comment]
Hi, it might be a good idea to add some date operations to the API at some point but for now you can get away with something like this

```lua
date_expiry = create_date_time()
date_expiry.month = date_expiry.month + 1


if (date_expiry.month > 12) then
  date_expiry.month = 1
  date_expiry.year = date_expiry.year + 1
end
```
