### ISSUE TITLE
File menu not working in NC 28

### ISSUE THREAD

**Issue by jorants** [Raudius/files_scripts#125]
Nextcloud 28 has changed the API for registering to the file menu, see https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#added-apis
This seems to break adding to the file menu for running scripts at the moment.

**Comment by Raudius** [comment]
Hi, I have not yet had time to integrate NC28. My goal is to do it before the end of the year.

If you have any more insights on other broken features (settings menu, flow, occ) would also save me some time

**Comment by Raudius** [comment]
The new files app integration is introduced with #126

It will be out with release 4.0.0 later this month
