### ISSUE TITLE
Add different input types

### ISSUE THREAD

**Issue by Raudius** [Raudius/files_scripts#13]
Currently its only possible to create input in textboxes. Would be nice to include a way to add different input types

* File/folder select
  * Would remove the need for the "request target directory" option
* Checkbox (true/false)
* Dropdown (multi + single select)

**Comment by Io-Qo** [comment]
I would appreciate different inputs very much, esp. for none tech-savy users. Also, input validation which could be done with a simple regular expression in the background could be helpful here.
