### ISSUE TITLE
Add functions to edit collaborative Tags

### ISSUE THREAD

**Issue by The-M1k3y** [Raudius/files_scripts#15]
It would be great to have the capability to edit tags on files.

This would allow for a (limited) integration with other flows.

My personal usecase here is to split and merge multiple PDFs and tag the resulting file for further processing with the "Workflow external scripts" to send the result to a printer.

**Comment by Raudius** [comment]
Nice idea! I have implemented some basic tagging functions. I also added a `shell_command` function which you might be able to use to send to the printer directly from the action.

These will be available in the next release (likely by the end of the week)
