### ISSUE TITLE
name_exact does not work for tags_find

### ISSUE THREAD

**Issue by Luux** [Raudius/files_scripts#150]
Hi there,

the `name_exact` parameter for `tags_find` does not seem to work correctly.
If I try the following code:
```
local tags = tags_find({name="released"})
add_message("Tag:"..tags[1].name)
if tags[1].name == "released" then
	local tags2 = tags_find({name=tags[1].name, name_exact=true})
end
```

I get the error message `Tag ("released", 1, 1) does not exist`, even though the message shows correctly with `Tag:released`, so the first statement (without `name_exact`) works and the name is also exact.

**Comment by Raudius** [comment]
Fixed with #151 will be included with the next release
