### ISSUE TITLE
Handling UTF in output file names

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#165]
Hi! I have created a script to unzip files:
```
-- Adding full paths
local input_path = meta_data(input_file).local_path
local output_path = meta_data(dir).local_path

-- Check if source file is zip then use unzip utility
if 
  	(table_contains(supported_formats, input_file_extension)) then   
        command_tpl = 'unzip "%s" -d "%s"'
		command = command_tpl:format(input_path, output_path)
        result = shell_command(command)

-- rescan folder with created file
		command2_tpl = 'sudo -u www-data php /usr/local/bin/occ files:scan --path="%s"'
		command2 = command2_tpl:format(output_path)
		result = shell_command(command2)
```

It works fine when the names of the zipped files are in Latin symbols. But if not it produces hashtagged codes. Eg, I have a zip archive `Тестовий каталог є.zip` which is the archive of the folder with the same name and it consists of 2 files `документ.odt` and `табличка.ods`.

When I use the lua script to unzip the file I am getting the following picture:

![image](https://github.com/Raudius/files_scripts/assets/5199030/be3fd26d-ab4f-420c-b0f0-c1de4e3f0e4b)

What should I correct to let the script tolerate non-Latin symbols?

If I unzip locally on the server it produces correct names of files.

UPD: replaced `unzip` with `unar` which produces file names with correct coding.

**Comment by Raudius** [comment]
Closing this issue because I dont think this is something that can be resolved by the files_scripts app. Probably due to the behaviour of the `unzip` program.

**Comment by ostasevych** [comment]
I've found the solution: just add `LC_ALL=C.utf8` before the command, eg
```
command_tpl = 'LC_ALL=C.utf8 7z x "%s" -o"%s" -aou' 
command = command_tpl:format(input_path, output_local_path)
```
