### ISSUE TITLE
Installing qpdf on the server

### ISSUE THREAD

**Issue by knot-split** [Raudius/files_scripts#177]
Hi,

As the docs report optional commands based on qpdf installation, what is the preferred way to keep qpdf on a nextcloud docker container?  As for myself, each time when following the procedure in AIO image, I add an environmental variable for optional APK, but it doesn't propagate to the into the containers.   Is there another way to script it in automatically without changing docker file?

**Comment by Raudius** [comment]
I am not familiar with the AIO container, but from looking at the docs it looks like you were already doing it the right way

https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-add-os-packages-permanently-to-the-nextcloud-container

**Comment by knot-split** [comment]
Okay, then it's a problem solved for here, but I'll look around some other nextcloud boards for ideas.
