### ISSUE TITLE
Transifex update

### ISSUE THREAD

**Issue by tobiasKaminsky** [Raudius/files_scripts#2]
Hi,

you use Transifex to translate and our system to update it.
This uses nextcloud-bot to commit the changes directly to master/stable branches.

Please add therefore @nextcloud-bot as an Admin via
https://github.com/Raudius/files_scripts/settings/access

**Comment by Raudius** [comment]
Hi Tobias, thanks for reaching out!

The request is already sent and is pending.

Related ticket: https://github.com/nextcloud/docker-ci/issues/382

**Comment by rakekniven** [comment]
You can close this one.
