### ISSUE TITLE
Access Comments for a File

### ISSUE THREAD

**Issue by michaelberg79** [Raudius/files_scripts#20]
Hi dears,

I want to access to the comments for a node, is there a possibilty?

best regards

**Comment by Raudius** [comment]
It should be possible, just need to add the api functions :)

Is there something specific you want to do with comments or just reading them?

**Comment by Raudius** [comment]
Add functions: `comment_create`, `comment_delete`, `comments_find` to the next release (`v1.3.0`)

Thanks for the suggestion!
