### ISSUE TITLE
Replicate "Share/Add to a project" function

### ISSUE THREAD

**Issue by AdhaiGrey** [Raudius/files_scripts#34]
Hi,

is there a possibility to recreate function of linking mutiple files into a project?

Best Regards,
Adhai

**Comment by Raudius** [comment]
Thanks for the suggestion I will try to add this for the next release ;)

**Comment by Raudius** [comment]
I have noticed that this feature was deprecated since Nextcloud 25, so it doesnt really make sense to add support for it :/
