### ISSUE TITLE
Snap php.ini

### ISSUE THREAD

**Issue by ThatEpicBanana** [Raudius/files_scripts#35]
The installation instructions tell to `append extension=lua.so to your php.ini`, but how do you do that on the Snap package? I've tried editing the php.ini within the `/snap/nextcloud/current/config/php` directory, but it doesn't work since snap files are in a read-only filesystem.

**Comment by Raudius** [comment]
Unfortunately this configuration needs to be managed by the snap package. You can try requesting it over at: https://github.com/nextcloud-snap/nextcloud-snap/issues

I saw they had already [added a configuration flag](https://github.com/nextcloud-snap/nextcloud-snap/commit/249d5575f838c607ff9924903a7974609e04f030) for installing the LDAP plugin, so they could do something similar. Not sure how feasible this as there might be security implications or they might simply not want to bloat the package.

**Comment by Raudius** [comment]
Also note that there is now a PHP-based interpreter included with this app. It is not as reliable as the plugin version, however if you test the scripts sufficiently they should do the job in most cases.
