### ISSUE TITLE
Function to get collaborative tags and user id of owner of the file

### ISSUE THREAD

**Issue by kselltrum** [Raudius/files_scripts#36]
It would be great to have the capability to get collaborative tags from selected file and user id of owner of the file (from  get_input_files()  in node object )

**Comment by Raudius** [comment]
Hey, thanks for the suggestions :)

They have now been addressed in:

- https://github.com/Raudius/files_scripts/pull/33
- https://github.com/Raudius/files_scripts/pull/44
