### ISSUE TITLE
lua extension not installed

### ISSUE THREAD

**Issue by s1787956** [Raudius/files_scripts#4]
Error Message "lua extension not installed on server" shown although lua is listed when executing php -m on server.
Any hints for a cause/solution?

**Comment by s1787956** [comment]
![php-cli](https://user-images.githubusercontent.com/22986426/182660070-9a3226ba-57fb-4db7-abb0-5de0122398f2.png)
![php-system](https://user-images.githubusercontent.com/22986426/182660080-715c0949-ff3b-4e3d-a45d-957b2b2868cc.png)

Thx. for the fast response!
Seems good to me. Although I cannot see my Extensions inside the `System` section.

**Comment by Raudius** [comment]
Thats strange.

In my case I have two ini files:

```
/etc/php/8.1/apache2/php.ini
```

and

```

/etc/php/8.1/cli/php.ini
```


The one that needs the extension is the server one (apache2) in my case.

**Comment by s1787956** [comment]
Got it to work with `phpenmod lua` and `a2enmod lua`.
Thx for the help and the nice app!
