### ISSUE TITLE
Can't add script in Nextcloud 25.0.4 + php8.1/lua5.4 extension enabled

### ISSUE THREAD

**Issue by s-rosenfeld** [Raudius/files_scripts#49]
Hi! Unable to add Lua script in File Actions app. This is an error:

![Screenshot_20230307_150624](https://user-images.githubusercontent.com/12949115/223405478-90c7d5cf-b158-4a2d-8beb-52451309d2ae.png)

Error message in Nextcloud log:

{
    "reqId": "MCZrWjVXp2fM883AJdfp",
    "level": 3,
    "time": "2023-03-07T11:09:17+00:00",
    "remoteAddr": "192.168.6.29",
    "user": "serg",
    "app": "files_scripts",
    "method": "POST",
    "url": "/apps/files_scripts/scripts",
    "message": "File scripts insert error",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "version": "25.0.4.1",
    "data": {
        "app": "files_scripts",
        "trace": "#0 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(329): OC\\DB\\Exceptions\\DbalException::wrap()#1 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(139): OC\\DB\\QueryBuilder\\QueryBuilder->executeStatement()\n#2 /var/www/nextcloud/apps/files_scripts/lib/Controller/ScriptController.php(104): OCP\\AppFramework\\Db\\QBMapper->insert()\n#3 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\\FilesScripts\\Controller\\ScriptController->create()\n#4 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#5 /var/www/nextcloud/lib/private/AppFramework/App.php(172): OC\\AppFramework\\Http\\Dispatcher->dispatch()\n#6 /var/www/nextcloud/lib/private/Route/Router.php(298): OC\\AppFramework\\App::main()\n#7 /var/www/nextcloud/lib/base.php(1047): OC\\Route\\Router->match()\n#8 /var/www/nextcloud/index.php(36): OC::handleRequest()\n#9 {main}"
    }
}

- Nextcloud 25.0.4
- PHP 8.1.2
- Lua 5.4
- Installation done as described in "Recommended" section in documentation.

what am I doing wrong?

**Comment by Raudius** [comment]
Hi, thanks for the report.

Unfortunately I did not do a great job with the logging on this one, so its hard to know whats going wrong. Looks like a database-related issue. 

What database are you using?  
Can you check that `oc_filescripts` and the `oc_filescript_inputs` tables exist in your database?

**Comment by s-rosenfeld** [comment]
> Hi, thanks for the report.
> 
> Unfortunately I did not do a great job with the logging on this one, so its hard to know whats going wrong. Looks like a database-related issue.
> 
> What database are you using? Can you check that `oc_filescripts` and the `oc_filescript_inputs` tables exist in your database?

My database: PostgreSQL 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

![Screenshot_20230307_172724](https://user-images.githubusercontent.com/12949115/223436671-4398f917-eb40-44f0-91ef-b3e9316f4276.png)

no such tables ... how to create them?

**Comment by Raudius** [comment]
Reinstalling the app might work. If not, you can try these occ commands in this order:

```
occ migrations:execute files_scripts 0100Date20220613
occ migrations:execute files_scripts 0100Date20220616
occ migrations:execute files_scripts 020100Date20221126
```

**Comment by s-rosenfeld** [comment]
> Reinstalling the app might work. If not, you can try these occ commands in this order:
> 
> occ migrations:execute files_scripts 0100Date20220613
> occ migrations:execute files_scripts 0100Date20220616
> occ migrations:execute files_scripts 020100Date20221126

Disable, Remove, Download and Enable - these steps did not help. Runing "occ migrations" helped, but it only worked in debug mode, and I didn't immediately realize that I needed to enable debugging. Anyway, now it worked as expected, big thaks!
