### ISSUE TITLE
Function "get_file_tags" confuses

### ISSUE THREAD

**Issue by ernolf** [Raudius/files_scripts#51]
Hi Raul,

first of all: thank you so much for this great app. I am a big fan and use it at a daily basis for a growing number of solutions.

The only thing that drives me nuts, is the new `get_file_tags()` function.

In the [Scripting Api](files_scripts/blob/master/docs/Functions.md) it says:

![image](https://user-images.githubusercontent.com/39901936/223724798-ace0e7c3-995b-4d9a-bba7-4910873f06d9.png)

I gues that is a tipo (*get_tags* instead of *get_file_tags*), same in this line:

https://github.com/Raudius/files_scripts/blob/89d5ceb480ae7a0f17bb7b86b8a1cbfc52c0776c/lib/Interpreter/Functions/Nextcloud/Get_File_Tags.php#L15

But now to my issue:
I am trying to get the tags from a previously tagged file.
My first step to understand how things work, is to return the echo into a text-file, like it works with all the meta_data etc. but in this case it does not work.
Since `get_file_tags()` returns a *table*, I used `table.concat()` to get a coma separated list of tags like this:

```
local files = get_input_files()
for _, input_file in ipairs(files) do
  local output_filename = input_file.name .. '.tags.txt'
  local out_folder = get_parent(input_file)
  if exists(out_folder, output_filename) then
    abort('Output file "' .. output_filename .. '" already exists. Skipping...')
    goto continue
  end
  local tags = get_file_tags(input_file)
  local tags_str = table.concat(tags, ',')
  new_file(out_folder, output_filename, tags_str)
  ::continue::
end

```

.. but it does not work.

But when I do:

```
  local tags = get_file_tags(input_file)
--  local tags_str = table.concat(tags, ',')
  new_file(out_folder, output_filename, #tags)
```

it returns the correct number of tags.

What am I doing wrong?

**Comment by Raudius** [comment]
Hi Raphael,

I think whats going wrong in your script is that the `get_file_tags` function returns a table of tag "objects" (see: https://github.com/Raudius/files_scripts/blob/master/docs/Admin.md#tag). I think your assumption was that it returned the tags as strings.

To get a better idea of what the output of `get_file_tags` looks like you can try this script on a tagged file:

```lua
local input_file = get_input_files()[1]
local tags = get_file_tags(input_file)

abort(json(tags))
```

I do agree though that the documentation is not great for this function (as well as the obvious mistake with the example). So I will try to write it up a bit better :)

**Comment by ernolf** [comment]
Many thanks for the quick response. Now that you've explained it to me, it all seems so natural and I almost feel a bit stupid that I didn't get it right away myself. But maybe it will ultimately help to make the instructions bulletproof!
