### ISSUE TITLE
File-picker does not work on directories

### ISSUE THREAD

**Issue by ernolf** [Raudius/files_scripts#55]
As described [here](blob/master/docs/Functions.md#get_target_folder): 

> ⚠️ DEPRECATED: Replace usage with user input of type "file-picker".
> Hint: set the accepted mimetypes to just `httpd/unix-directory` to limit file picker to directories.

and [here](blob/master/docs/Admin.md#user-input):

> Note: to allow a user to pick a folder the `httpd/unix-directory` mimetype must be added to the filepick options.

one should replace the "*Request target folder*" mechanism, linked to get_target-folder() with the Filepicker from the "*User inputs*" mechanism, linked to get_input().

Now to the issue:

* The Filepicker window opens, I can select folders but it ain't possible to choose the folder. The blue "choose" button stays darkens. When no mime type restriction is given, only files are posible to choos as well, no directories.

**Comment by ernolf** [comment]
I apologize, I don't know why it didn't work before, but it works now

**Comment by ernolf** [comment]
OK, I understand why it did not work, I falsly thought that the mimetype should be http/unix-directory instead of httpd/unix-directory.

**Comment by feefladder** [comment]
So for anyone coming here: it is important to press the arrow button when selecting a MIME type. Then it will be added to a little list below and then save it!
