### ISSUE TITLE
Multi-select - strange behaviour

### ISSUE THREAD

**Issue by ernolf** [Raudius/files_scripts#56]
When selecting with the Multi-select mechanism, the first option returns (when selected) an error.
Also, the selected item does not remain visible in the list after it has been selected.

Reproduce with:

![image](https://user-images.githubusercontent.com/39901936/224507529-2c49051d-5c1f-433b-aa5f-b4741c432400.png)

Testing this action returns the choosen animal but dog. When choosing dog, it returns "Action failed unexpectedly"

Confusing: no matter what animal i choose, only "dog" is visible.

Did I missunderstand something again?

**Comment by Raudius** [comment]
Fixed with #62
