### ISSUE TITLE
tag_file_unassign() dosn't works on folders

### ISSUE THREAD

**Issue by s-rosenfeld** [Raudius/files_scripts#57]
As far as I understand the problem is here:

![Screenshot_20230314_122402](https://user-images.githubusercontent.com/12949115/224940157-34a447a9-d38a-40bf-afa3-c01ad31403b1.png)

On files this function works as expected.

**Comment by s-rosenfeld** [comment]
With this fix it works as expected:

![Screenshot_20230314_123519](https://user-images.githubusercontent.com/12949115/224943352-6060f93b-b346-49f0-9ea0-3774f8bc5299.png)

**Comment by Raudius** [comment]
Fixed with #63
