### ISSUE TITLE
meta_data() doesn't works with folders on external storage

### ISSUE THREAD

**Issue by s-rosenfeld** [Raudius/files_scripts#58]
The issue locate in

/var/www/nextcloud/apps/files_scripts/lib/Interpreter/Functions/Files/Meta_Data.php:41

Call of $node->getStorage()->getLocalFile() for folder generate exception InvalidTypeException, and it doesn't catch in your code.

**Comment by ernolf** [comment]
I can get all meta_data() from files as well as from folders.

**Comment by s-rosenfeld** [comment]
> I can get all meta_data() from files as well as from folders.

You can get all metadata when a folder is in local storage. But if the storage is external (eg SMB/CIFS), the return value is NIL. Delow is an example script:

![1](https://user-images.githubusercontent.com/12949115/226163314-4b30528c-c9bd-4aaf-b961-e8791c72ff95.png)

This is the result of working on a folder that is on external storage:

![2](https://user-images.githubusercontent.com/12949115/226163391-20b76545-b0e6-4213-b9c6-e2afa2c83c29.png)

**Comment by Raudius** [comment]
Fixed with #65
