### ISSUE TITLE
file_move() doesn't works on folders

### ISSUE THREAD

**Issue by s-rosenfeld** [Raudius/files_scripts#59]
The following changes fixes the issue:

![Screenshot_20230315_112135](https://user-images.githubusercontent.com/12949115/225236446-6c46ce0e-2c99-4bd7-bea0-44513b775591.png)

![Screenshot_20230315_112306](https://user-images.githubusercontent.com/12949115/225236477-e5ba2067-0021-4891-8423-166b8f08df0e.png)

**Comment by Raudius** [comment]
Fixed https://github.com/Raudius/files_scripts/pull/64
