### ISSUE TITLE
Is it possible to get Node by file path?

### ISSUE THREAD

**Issue by s-rosenfeld** [Raudius/files_scripts#61]
I need to get a list of Nodes in an arbitrary folder. There is a directory_listing() function here, but it needs to pass an argument of type Node, not a string. How to solve this problem?

**Comment by Raudius** [comment]
You would have to test it but I think something like this would work for now:

```lua
-- Relative path from the user's home directory
local full_path = 'folderA/folderB/file.txt'

-- Using string:match, string:sub function...
local parent = 'folderA/folderB/'
local file_name = 'file.txt'

-- Manually create node
local node = {
  name= file_name,
  path= parent
}
```

Typically the `id` attribute is part of the node, however I dont think this is used internally at the moment. However I will keep this issue open to add a function to make this possible

**Comment by Raudius** [comment]
Thinking about it you could even get the `id` by inflating the node with the `meta_data` function

```lua
local node = {
  name= file_name,
  path= parent
}

node = meta_data(node)
```

**Comment by s-rosenfeld** [comment]
> Thinking about it you could even get the `id` by inflating the node with the `meta_data` function
> 
> ```lua
> local node = {
>   name= file_name,
>   path= parent
> }
> 
> node = meta_data(node)
> ```

Yes, it's worked! Thank you :)

**Comment by Raudius** [comment]
On further thought, I have decided not to add such a function to the API.

The current work-around is sufficient and should work for the foreseeable future.

**Comment by 1358** [comment]
It would be nice if [the code snippet how to create a Node by specifying path and name](https://github.com/Raudius/files_scripts/issues/61#issuecomment-1475956801) could be added to the [Node-Description in the admin readme](https://github.com/Raudius/files_scripts/blob/2103796e25a8b11996aadaee21e2671fa2e938cc/docs/Admin.md?plain=1#L42)
