### ISSUE TITLE
[Checkbox] unsatisfactory behavior

### ISSUE THREAD

**Issue by ernolf** [Raudius/files_scripts#78]
When using the user input "Checkbox", a litlle slider appears and when clicking once on it, it returns true but no optical feedback if checkbox is "Set".
Once the input is clicked, it is impossible to unset the checkbox again, once clicked, it stays returning "true".

How to reproduce:

![image](https://user-images.githubusercontent.com/39901936/227721081-606d0828-0806-4e0f-90d3-93fef5143e4f.png)

Behaviour
Not set:

![image](https://user-images.githubusercontent.com/39901936/227721150-73a85dab-9b32-4937-b8aa-ae483034d7f6.png)

Set:

![image](https://user-images.githubusercontent.com/39901936/227721195-3aa90cc9-a32a-4267-969d-b385b28b48d8.png)

**Comment by Raudius** [comment]
Thanks for the report. I have fixed it and squeezed it in as part of an RC release. So if you need this feature you can install it with:  

```
occ app:update files_scripts --allow-unstable
```

I didnt make this a full release for a few reasons
 - I removed the deprecated API functions, and I want to give a bit more time for users to move away from these
 - I added the option to make scripts optionally available on public shares (I am still testing this as I am somewhat worried on the security angle)
 - I have recently been moving fast and breaking things with the app and I am afraid of doing the same with this release :upside_down_face:
