### ISSUE TITLE
Add ffmpeg commands

### ISSUE THREAD

**Issue by medismail** [Raudius/files_scripts#8]
This lib https://github.com/PHP-FFMpeg/PHP-FFMpeg can be added for helping to convert video/audio or extracting audio or take screenshot from video and more tools.
Also have this 3 nextcloud apps already use ffmpeg:
https://apps.nextcloud.com/apps/workflow_media_converter
https://apps.nextcloud.com/apps/video_converter
https://apps.nextcloud.com/apps/ncdownloader

**Comment by Raudius** [comment]
Thanks for the suggestion!

Should definitely be possible to add some ffmpeg functions to the API. 

Since there is a lot the FFMpeg can do, what specific functions would you personally find useful?

**Comment by medismail** [comment]
Welcome :)
I think most used functions is:
- Extract audio from video and convert to mp3 $ ffmpeg -i video -map 0:a -c:a libmp3lame -y audio.mp3
- Convert any video format to mp4 $ ffmpeg -i video -c:v copy -c:a copy -y output.mp4
- Convert any audio format to mp3 $ fffmpeg -i audio -c:a libmp3lame -y audio.mp3
- Extract a part of audio or video (should have same extension in input and output or that will change the format also) $ ffmpeg -i input -ss 00:00:10 -to 00:00:30 -codec copy -y output

**Comment by Raudius** [comment]
Just merged the changes, will be included with the next release.

You can see the documentation here:  https://github.com/Raudius/files_scripts/blob/master/docs/Functions.md#ffmpeg

It should be possible to do all the things you suggested, additionally you can also change things like the resolution, audio/video bitrates, and overriding the default codecs for the selected format.
