### ISSUE TITLE
share handling

### ISSUE THREAD

**Issue by ArnY** [Raudius/files_scripts#85]
Hello,

I haven't found anything in the documentation related to share handling. It would be really useful to be able deal with share the same was we can deal with files and folder: list shares (in a given folder, as a whole?) check if a node is a share, move share, delete share, create_share.

Is that already possible and if not, is that something that could be done sometimes?

Thanks!

**Comment by Raudius** [comment]
Will be added as part of the 3.0.0 release.

PR here: https://github.com/Raudius/files_scripts/pull/99
