### ISSUE TITLE
cannot move / delete / rename files in flow

### ISSUE THREAD

**Issue by baanan** [Raudius/files_scripts#87]
**To Reproduce:**
- create an action with the code:
```
files = get_input_files()

for i, file in ipairs(files) do
  name = file.name
  
  if name == "a.txt" then
    file_move(file, nil, "b.txt")
  end
end
```
- create a flow like this

![image](https://user-images.githubusercontent.com/40611336/229366023-965ff946-a203-4e10-a787-b8ffb7a6a9b2.png)

- create a text file named `a.txt`, notice how it doesn't rename
- run the action, it should rename now
- rename it again to `a.txt`, it should rename but it doesn't

**Comment by Raudius** [comment]
Finally got around to look into this issue.

I was able to reproduce, and found a log message regarding the file being locked. Could fix it by adding a `file_unlock` call before the rename:

```lua
files = get_input_files()

for i, file in ipairs(files) do
  name = file.name
  
  if name == "a.txt" then
    file_unlock(file) -- UNLOCK THE FILE
    file_move(file, nil, "b.txt")
  end
end
```
