### ISSUE TITLE
New function: move/copy file as root

### ISSUE THREAD

**Issue by Io-Qo** [Raudius/files_scripts#9]
- a simple extension/addtion to file_move and copy_file to allow moving files as root for automated collaborations without shares (e.g. moving files to another department)

**Comment by Raudius** [comment]
Thanks for the suggestion. 

Although it can be dangerous to allow users to perform actions that generally fall out of their permissions on the server (such as writing to another user's folder), I see no harm in including it the API. Use at your own risk :p

**Comment by Raudius** [comment]
Merged the changes! They should be in for the next release :wink:
