### ISSUE TITLE
Install from app store only

### ISSUE THREAD

**Issue by Andreas-Kainz** [Raudius/files_scripts#90]
Hi,

Would it be possible to use the app direct from the app store and only for specific features additional software will be needed.

I have a managed nextcloud where I can install apps, but no option to install additional software.

**Comment by Raudius** [comment]
Hi Andreas. 

What you describe is already the case, you can use the app without any additional software. You will need to enable the "Experimental interpreter" option in the settings.

This will use the PHP-based interpreter, which is not as complete or efficient as the PHP extension version. Also some API functions which rely on specific software packages will not work (namely the PDF and FFMPEG functions).
