### ISSUE TITLE
Script repository 

### ISSUE THREAD

**Issue by Andreas-Kainz** [Raudius/files_scripts#91]
Would it be useful to have a script repository with file_actions which you can activate if wanted or at least which users can use as template for there needs.

Or at least a link to a repository where you can get some inspiration. 

I'm thinking on something like
https://store.kde.org/browse?cat=102&ord=latest

**Comment by Raudius** [comment]
This is a nice idea. I will have to think about how to implement this and how much time it will take.

For now if you have any scripts you would like to share, feel free to make a Pull Request adding them to the [`examples/`](https://github.com/Raudius/files_scripts/tree/master/examples) directory.

**Comment by ostasevych** [comment]
Would that be possible to create local repositories of scripts? I mean, allow save them and export/import in the form of JSON files?

**Comment by ostasevych** [comment]
Hey, just to continue this thread. Are any chances to export created scripts in some form, eg json, which will include:
- text of the script
- programmed controls in UI
Of course, to allow import them by other users.

This will allow to create the repository of scripts.

**Comment by Raudius** [comment]
@ostasevych 

It is now possible (since `files_scripts:3.1.0`) to import/export scripts in json using
 
`occ files_scripts:import` and `occ files_scripts:export`

See: https://github.com/Raudius/files_scripts/pull/110

**Comment by ostasevych** [comment]
> @ostasevych
> 
> It is now possible (since `files_scripts:3.1.0`) to import/export scripts in json using
> 
> `occ files_scripts:import` and `occ files_scripts:export`
> 
> See: #110

Hi! Will it be possible to add the UI switch to export/import scripts? Eg here 
![image](https://github.com/Raudius/files_scripts/assets/5199030/1a8d959c-76d1-4242-af76-e1f17af2c9c3)
