### ISSUE TITLE
file_open

### ISSUE THREAD

**Issue by IS27-Particle** [Raudius/files_scripts#93]
Would be nice to build out scripts which end up opening specified files for editing or viewing purposes.

**Comment by Raudius** [comment]
Do you mean that after the script is done running it would open the file with Text, Office, Image viewer, etc.?

**Comment by IS27-Particle** [comment]
Yes! That's precisely what I'm looking for!   Maybe it could take advantage of coroutines in lua and wait for the file close?

**Comment by Raudius** [comment]
Yeah its not really possible to do anything fancy like that. We can just return a list of files to open from the script to the frontend and have the viewer app handle them.

Granted if there is no registered app to open the file then nothing will happen.

**Comment by IS27-Particle** [comment]
That's basically what I'm after?
Like if I have the file node I'd like to pass that off to Nextcloud files to trigger opening in whichever editor/viewer is set up?

**Comment by Raudius** [comment]
Will be added as part of the 3.0.0 release

See PR: https://github.com/Raudius/files_scripts/pull/100
