### ISSUE TITLE
Feature: Dynamic inputs

### ISSUE THREAD

**Issue by feefladder** [Raudius/files_scripts#96]
This is maybe a bit difficult, but it would be nice to be able to have inputs that are added/removed based on some input, like a file/folder. For example, in the directory tree example, you'd be able to select which files in the specific folder you want printed to the txt file.

I think this would be possible with a script that creates a script on-the-fly that adds necessary inputs. Any pointers welcome!

**Comment by Raudius** [comment]
I cant really think of a feasible way to achieve this at the moment. Will leave the issue open, but I am tempted to say this one is going to be a `wontfix`

**Comment by Raudius** [comment]
I have decreasingly less time to maintain this app, and the complexity of this task is too large to justify even attempting so unfortunately this feature will not get done any time soon. 

Will close the ticket for now to keep the open issues clean.
